### PR TITLE
Extract test vectors to JSON files

### PR DESCRIPTION
**Pull request by guggero**
I've extracted the test vector data out of the test source file into separate JSON files. Additionally, I improved the test coverage minimally by adding some very long input strings for aezHash

### CODE REVIEW

**Comment by Yawning** [comment]
The idiomatic sub-directory for test data is `testdata` as the go tool has a special support (as in, it ignores it) for such things.

**Comment by guggero** [comment]
Ah, I didn't know that. I'm fairly new to go... But thank you for the hint. I renamed the directory.

**Comment by guggero** [comment]
I've simplified the code that reads the`testdata` files so it's much cleaner.

**Comment by Yawning** [comment]
Merged as ec7426b4492636b9b39cb6e173e7423500107163 after running `go fmt`.

Thanks.

**Pull request closed without merging**
